name: Build LaTeX PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Setup TeXLive
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CH01_S1_3.tex
  
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf
